regCenter:
  serverList: 192.168.56.11:2181,192.168.56.12:2181,192.168.56.13:2181
  namespace: elastic-job-lite-springboot

stockJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=Chengdu0,1=Chengdu1