#服务配置
server:
  port: 8080
spring:
  http:
    encoding:
      charset: UTF-8


#文件路径配置
content:
  repository:
    url: https://github.com/telundusiji/kaleidoscope.git
    username: telundusiji
    password: h2470893279
  file:
    used: .md
    path:
      windows: D:\opt\content
      linux: /opt/content
git:
  install:
    path:
      windows: D:\programs\Git
      linux: